### ISSUE TITLE
[FEATURE] 크롤링-유튜브 코드

### ISSUE THREAD

**Issue by smyk5537** [NL-to-dataset/NTD-scrapers#3]
## 📍 구현 기능
- 키워드 추출 결과로 실시간 유튜브 크롤링 데이터셋 생성

## 🛠 작업 내용
- [ ] 유튜브 크롤링 코드 수정
- [ ] 유튜브 크롤링 질의어 수정(시나리오 다양하게)
- [ ] 키워드 추출 모듈과 크롤링 코드 연결

## 📢 추가 의논 사항
- 크롬 드라이브 잦은 업데이트로 주기적으로 코드 유지 관리 해야함

## 🚨 주의 사항
- 구현하며 발견한 주의 사항이나 **꼭 확인했으면 하는 로직**에 대한 설명

**Comment by Jjinyshin** [comment]
# 버리자
